language: ruby
node_js:
  - node
rvm:
  - 2.6
addons:
  chrome: stable
before_install:
  - nvm install v15.0.1
install:
  - bundle install
  - npm install
script: bundle exec rake spec
deploy:
  provider: rubygems
  api_key:
    secure: virkIxAWVVsS4YMgSUVuomyduiTSKuEVSPBDhrFT5A1C1slHccWLQFxhIYYRjOQcH3OipKvJvKWmprJAOO/8pczOMPZXyEIMFsykpk2kIdeYfB9RIvH0xGKwPqCzMkElexPn0TcCPMT6xk70vE2pJuL85q2rqRykhpJhRcNNIDbR6B68M8Rn5Fa5VhyWRI7x94+0hnzOAqZpk0ufijsWl6T8TcQZjh18ysTwxClrVHci29c4ETbRa/0LbEunxGnI6U32byayq7ojhZXBB0eA7jqX8uiEwNA+JLgXOx/FkdYod+fVO8q3J4v/+6D8g1rxoFGxTv8veb/QfSSGwE4pYovBksIoiA4dtvEBfbia2xJlHKCSRx1JB0d05jRvS0T8K1M30mibfhIA5gB1oIO6uHOFLEbHQ6LmJxOvRxO/6VDdAO4QqRbyrGiR8H+9m4q1t+D0tPi19mTxs2RXJ4ftAv3fqkmM4TQci7cizNIIKAlXpu4/NMyjsq4EUY7unqLzGenupEkw12AhGT0w9tci3zeAvcEurUQez5C7gKHFbZWKSbCcplVw/zHTR+0c8jPhzShVxR169lC2U27/1zxwvOlrwqjIJPB9Cn84Nx38E1h9hZJNqzMRvjle4EI7XARsUNkX/PnKDFyetlwgW7L+gjgaGtxoEZYn8FxvY/4q4Do=
    gemspec: Dhalang.gemspec
  on:
    branch: master
    tags: true
