name: Publish
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: bundle exec rake spec
      - run: gem build -o Dhalang.gem Dhalang.gemspec
      - run: gem push Dhalang.gem